### ISSUE TITLE
Caching not reliable on MSVC with additional flags

### ISSUE THREAD

**Issue by mariuszwicker-cnhind** [emzeat/linter-cache#7]
The commandline passed to ccache seems to be interpreted the wrong way as ccache is not handling MSVC specific options the correct way. Might need to stop hardcoding the `CCACHE_COMPILERTYPE=clang` and possibly also use `clang-cl` on some platforms.

In addition it would be great to provide flexibility for overriding this from the outside.

**Comment by emzeat** [comment]
Fix included in a4c451ceac414f8acf7d76985f03d64e6caf2142 released as v0.2.4
